#默认服务器
neo4jServer:
  url:
    #bolt://10.15.97.89:7687
    bolt://10.10.15.27:7687
    #bolt://10.17.205.190:7687
    #bolt://127.0.0.1:7678
    #bolt://10.10.17.10:7687
  user:
    neo4j
  password:
    123456
    #ywbz10

#company和relationShip数据来源
mssql:
  mssql://app:app127@10.10.15.44/CRDB

#ITCode2->ITName
dictionaryServer:
  host: 
    10.10.15.129
  port:
    #8009
    8010
  path:
    #/lookup
  
#node的label、index等相关信息，默认使用nodeLabelName1、nodeIndexName1
indexInfo:
  nodeLabelName1:
    company
  nodeIndexName1:
    ITCode2
  nodeLabelName2:
    company
  nodeIndexName2:
    ITCode2

#设置查询neo4j server的超时时间
# lookupTimeout: 
#   150000                                         #超时设置15s
  
#设置加入预热的path条件
warmUp_Condition:
  queryNeo4jCost:
    2000                                        #查询neo4j所需时间
  queryNeo4jRecords:
    200                                        #查询neo4j返回记录数

#主动预热path的redis地址
warmUp_RedisInfo:
  url_2:
    redis://:finchina@10.15.97.135:6679/2       #存放ITCode   
    #redis://:finchina@10.10.15.126:8097/0  
  url_3:
    redis://:finchina@10.15.97.135:6679/3       #存放paths
    #redis://:finchina@10.10.15.126:8097/0  
  TTL:
    86400
    
#设置cache的信息
NodeCache:
  stdTTL: 
    21600000
  # checkperiod: 
  #   600
  # useClones: 
  #   false
  redisUrl:                                     #存放paths cache
    redis://:finchina@10.15.97.135:6679/10      #注意：需指定一个独立使用的db, 清空缓存时需要清空db中的所有内容
  autoFlushCache:                               #程序重启是否清空缓存
    #'true'
    'fasle'

#redis存储数据的keyName
redisKeyName:
  conditionsKey:
    warmUpKey_conditions                         #记录预热数据的conditions

#设置各个路径的查询深度
pathDepth:
  IVDepth:
    5                                           #直接投资关系路径深度
  IVBDepth: 
    5                                           #直接被投资关系路径深度
  FUDepth:
    3                                           #全部路径深度
  DIDepth:
    3                                           #单个企业直接投资关系路径深度
  DIBDepth:
    3                                           #单个企业直接被投资关系路径深度
  CIVDepth:                                     
    4                                           #共同投资关系路径深度
  CIVBDepth:
    4                                           #共同被投资关系路径深度
  GTDepth:
    3                                           #担保关系路径深度
  GTBDepth:
    3                                           #被担保关系路径深度

#定时触发主动查询需要预热的path数据
schedule:
  hour:
    12
  minute:
    0       

#控制任务并发, 加锁机制信息
lockInfo:
  redisUrl:
    - redis://:finchina@10.15.97.135:6679/4
    - redis://:finchina@10.15.97.135:6679/5
  resource:
    - 'lockTimingWarmUpPaths_terminal'          #为lockTimingWarmUpPaths方法加锁
  TTL:
    #- 600000
    - 21600000                                  #加锁时间, 设置6h

#日志相关信息设置
logInfo:
  maxLogSize:
    20480000